
export const accounts = [
  {
    id: 1,
    banned: false,
    userName: "@TomsLider",
    login: "TOMS LIDER",
    firstName: "Toms",
    lastName: "Kagenou",
    email: "lidirgame@gmail.com",
    userRole: "Coder",
    password: "12345678",
    img: "/assets/avatars/img_2.jpg",
    followers: [ "@AniToku", "@AnyBear", "@ProfGorge", "@Dipley",    "@BOT_1", "@BOT_2", "@BOT_3", "@BOT_4", "@BOT_5", "@BOT_6", "@BOT_7", "@BOT_8", "@BOT_9", "@BOT_10",],
    following: ["@AniToku"],
  },

  
  {
    id: 2,
    banned: false,
    userName: "@AniToku",
    login: "AniToku",
    firstName: "Toms",
    lastName: "Kageno",
    email: "anitoku@gmail.com",
    userRole: "YouTuber",
    password: "12345678",
    img: "/assets/avatars/img_3.jpg",
    followers: ["@TomsLider"],
    following: ["@TomsLider"],
    properties: []
  },
  {
    id: 3,
    banned: false,
    userName: "@ProfGorge",
    login: "Uchiha Gorge",
    firstName: "Gorge",
    lastName: "Stefnson",
    email: "gorge0stefnson@gmail.com",
    userRole: "Gamer",
    password: "12345678",
    img: "/assets/avatars/img_1.jpg",
    followers: [],
    following: ["@TomsLider"],
    properties: []
  },
  {
    id: 4,
    banned: false,
    userName: "@AnyBear",
    login: "Any Bear",
    firstName: "Asuna",
    lastName: "Elinburg",
    email: "anybear0100@gmail.com",
    userRole: "YouTuber",
    password: "12345678",
    img: "none",
    followers: [],
    following: ["@TomsLider"],
    properties: []
  },
  {
    id: 5,
    banned: true,
    userName: "@Dipley",
    login: "Dipleyjon",
    firstName: "Murod",
    lastName: "GG",
    email: "dipleyjonuz@gmail.com",
    userRole: "YouTuber",
    password: "12345678",
    img: "/assets/avatars/img_4.webp",
    followers: [],
    following: ["@TomsLider"],
    properties: []
  },
  




  {
    id: 6,
    banned: false,
    userName: "@BOT_1",
    login: "BOT 1",
    firstName: "RandomBot",
    lastName: "Houzing",
    email: "randombot1@gmail.com",
    userRole: "Coder",
    password: "12345678",
    img: "",
    followers: [],
    following: ["@TomsLider"],
    properties: []
  },
  {
    id: 7,
    banned: false,
    userName: "@BOT_2",
    login: "BOT 2",
    firstName: "RandomBot",
    lastName: "Houzing",
    email: "randombot2@gmail.com",
    userRole: "Coder",
    password: "12345678",
    img: "",
    followers: [],
    following: ["@TomsLider"],
    properties: []
  },
  {
    id: 8,
    banned: false,
    userName: "@BOT_3",
    login: "BOT 3",
    firstName: "RandomBot",
    lastName: "Houzing",
    email: "randombot3@gmail.com",
    userRole: "Coder",
    password: "12345678",
    img: "",
    followers: [],
    following: ["@TomsLider"],
    properties: []
  },
  {
    id: 9,
    banned: false,
    userName: "@BOT_4",
    login: "BOT 4",
    firstName: "RandomBot",
    lastName: "Houzing",
    email: "randombot4@gmail.com",
    userRole: "Coder",
    password: "12345678",
    img: "",
    followers: [],
    following: ["@TomsLider"],
    properties: []
  },
  {
    id: 10,
    banned: false,
    userName: "@BOT_5",
    login: "BOT 5",
    firstName: "RandomBot",
    lastName: "Houzing",
    email: "randombot5@gmail.com",
    userRole: "Coder",
    password: "12345678",
    img: "",
    followers: [],
    following: ["@TomsLider"],
    properties: []
  },
  {
    id: 11,
    banned: false,
    userName: "@BOT_6",
    login: "BOT 6",
    firstName: "RandomBot",
    lastName: "Houzing",
    email: "randombot6@gmail.com",
    userRole: "Coder",
    password: "12345678",
    img: "",
    followers: [],
    following: ["@TomsLider"],
    properties: []
  },
  {
    id: 12,
    banned: false,
    userName: "@BOT_7",
    login: "BOT 7",
    firstName: "RandomBot",
    lastName: "Houzing",
    email: "randombot7@gmail.com",
    userRole: "Coder",
    password: "12345678",
    img: "",
    followers: [],
    following: ["@TomsLider"],
    properties: []
  },
  {
    id: 13,
    banned: false,
    userName: "@BOT_8",
    login: "BOT 8",
    firstName: "RandomBot",
    lastName: "Houzing",
    email: "randombot8@gmail.com",
    userRole: "Coder",
    password: "12345678",
    img: "",
    followers: [],
    following: ["@TomsLider"],
    properties: []
  },
  {
    id: 14,
    banned: false,
    userName: "@BOT_9",
    login: "BOT 9",
    firstName: "RandomBot",
    lastName: "Houzing",
    email: "randombot9@gmail.com",
    userRole: "Coder",
    password: "12345678",
    img: "",
    followers: [],
    following: ["@TomsLider"],
    properties: []
  },
  {
    id: 15,
    banned: false,
    userName: "@BOT_10",
    login: "BOT 10",
    firstName: "RandomBot",
    lastName: "Houzing",
    email: "randombot10@gmail.com",
    userRole: "Coder",
    password: "12345678",
    img: "",
    followers: [],
    following: ["@TomsLider"],
    properties: []
  },
];



